{{ if eq .Values.Deployment.type "CQ-Pair" }}
{{ if .Values.Secret.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.Common.name }}-command-secret
  namespace: {{ .Values.Common.namespace }}
  {{ with .Values.Secret.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
data:
  {{- range .Values.Deployment.containers.env }}
    {{ if eq .name "ASPNETCORE_ENVIRONMENT"}}
  appsettings.{{ .value }}.json: |-
    {{ else }}
  appsettings.Production.json: |-
    {{ end }}
  {{ end }}
    {{$.Files.Get  "appsettings-query.json" | nindent 6 | b64enc -}}
{{ end }}
{{ end }}
