{{ if .Values.ExtraSecret.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.ExtraSecret.name }}
  namespace: {{ .Values.Common.namespace }}
  {{ with .Values.ExtraSecret.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
data:
    {{ if .Values.ExtraSecret.data.fromFile }}
    {{ $filename := .Values.ExtraSecret.fileName }}
  {{ .Values.ExtraSecret.data.key }}: |-
    {{ $.Files.Get  $filename | nindent 6 | b64enc -}}
    {{ else }}
  {{ .Values.ExtraSecret.data.key }}: {{ .Values.ExtraSecret.data.value | b64enc }}
    {{ end }}
{{ end }}