---
- name: Configure keepalived
  when: keepalived_role == "MASTER"
  template:
    src: keepalived_master.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Configure keepalived
  when: keepalived_role == "BACKUP"
  template:
    src: keepalived_backup.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy
  
- name: Configure sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
  notify: Restart keepalived

- name: Enable services for automatic start
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - haproxy
    - keepalived