- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{groups['haproxy-cluster-ip'][0]}} {{haproxy_cluster_name}}
      {{groups['haproxy-cluster-ip'][0]}} form.{{haproxy_cluster_name}}
      {{groups['haproxy-cluster-ip'][0]}} public.{{haproxy_cluster_name}}
